### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by BlenderDefender** [PidgeonTools/PidgeonRenderFarm#6]
```[tasklist]
### Tasks
- [ ] https://github.com/PidgeonTools/PidgeonRenderFarm/issues/7
- [ ] https://github.com/PidgeonTools/PidgeonRenderFarm/issues/9
- [ ] https://github.com/PidgeonTools/PidgeonRenderFarm/issues/8
- [ ] https://github.com/PidgeonTools/PidgeonRenderFarm/issues/10
```
